services:
  - type: web
    name: expensehub-backend
    env: node
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
